# SPDX-FileCopyrightText: 2014 MicroPython & CircuitPython contributors (https://github.com/adafruit/circuitpython/graphs/contributors)
#
# SPDX-License-Identifier: MIT

name: Build CI

on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    types: [rerequested]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-arm:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        board: [raspberry_pi_pico]
    steps:
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - uses: actions/checkout@v2.2.0
        with:
          submodules: false
          fetch-depth: 1
      - name: Get CP deps
        run: python tools/ci_fetch_deps.py ${{ matrix.board }} ${{ github.sha }}
      - name: Install dependencies
        run: |
          sudo apt-get install -y gettext
          pip install -r requirements-ci.txt -r requirements-dev.txt
          wget --no-verbose https://adafruit-circuit-python.s3.amazonaws.com/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
          sudo tar -C /usr --strip-components=1 -xaf gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
      - name: Versions
        run: |
          gcc --version
          arm-none-eabi-gcc --version
          python3 --version
      - name: mpy-cross
        run: make -C mpy-cross -j2
      - name: Setup build failure matcher
        run: echo "::add-matcher::$GITHUB_WORKSPACE/.github/workflows/match-build-fail.json"
      - name: build
        run: python3 -u build_release_files.py
        working-directory: tools
        env:
          BOARDS: ${{ matrix.board }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.board }}
          path: bin/${{ matrix.board }}
